/// Curated Kurmancî → Türkçe sözlük (~330 giriş).
///
/// Bu Map artık sözlük sisteminin TEK kaynağı değil; `tools/ferheng_pipeline/`
/// bunu okur ve `assets/ferheng/legacy_meanings.json` ile Firestore'a aktarır.
/// Senkron arama ve günlük meydan-okuma deterministic seçimi için sync API
/// olarak burada kalır.
///
/// Yeni kod tam metadatalı arama için [FerhengService.getOrFallback] kullanmalı:
/// definitions (kmr+tr), examples, etymology, kategori vb. erişimi sağlar.
@Deprecated('Yeni kod için FerhengService.getOrFallback() kullan; bu sınıf '
    'sadece senkron API ihtiyacı olan çağıranlar için tutuluyor.')
class KurdishMeanings {
  static const Map<String, String> _meanings = {
    // 2 harf
    'AV': 'su',
    'EZ': 'ben',
    'TU': 'sen',
    'AX': 'toprak',
    'DI': '-de / -da (edat)',
    'JI': '-den / için',
    'BO': 'için',
    'NA': 'hayır, değil',
    'LI': '-de / -da',
    'KU': 'ki, olan',
    'EV': 'bu',
    'YA': 'ya, veya',
    'BÊ': 'olmadan, -siz',
    'RÊ': 'yol',
    'NÊ': 'hayır (kuvvetli)',
    'DU': 'iki',
    'SÊ': 'üç',
    // 3 harf
    'BAV': 'baba',
    'DIL': 'kalp, gönül',
    'ROJ': 'gün, güneş',
    'MAL': 'ev',
    'NAV': 'isim; içi',
    'SER': 'baş, üst',
    'GEL': 'halk, millet',
    'PAR': 'pay, hisse',
    'ÇEM': 'nehir, dere',
    'GOL': 'göl',
    'KAL': 'ihtiyar, yaşlı',
    'PIR': 'çok; köprü',
    'DER': 'kapı; dışarı',
    'GUL': 'çiçek, gül',
    'LAW': 'genç erkek',
    'HEV': 'birlikte, beraber',
    'SAL': 'yıl',
    'ŞEV': 'gece',
    'YEK': 'bir',
    'DAR': 'ağaç',
    'KEW': 'keklik',
    'BIR': 'biraz',
    'DIN': 'din; başka',
    'GAV': 'adım; an',
    'MIN': 'benim',
    'PEL': 'yaprak',
    'REV': 'kaçış',
    'SOZ': 'söz, vaat',
    'CAN': 'can, ruh',
    'KAN': 'kan',
    'ZAN': 'bil, bilmek',
    'DAY': 'anne',
    'KUR': 'oğul',
    'BAZ': 'kartal; rüzgar',
    'DAL': 'dal (ağaç)',
    'KAR': 'iş',
    'MAR': 'yılan',
    'NAL': 'nal (at)',
    'SAR': 'soğuk',
    'WAR': 'yer, yurt',
    'SOR': 'kırmızı',
    'ŞER': 'savaş',
    'RON': 'aydınlık',
    'TEV': 'hepsi, tüm',
    'NET': 'temiz, net',
    'RAN': 'uyluk',
    'ŞAN': 'şan, ün',
    'HAN': 'han, kervansaray',
    'JAR': 'zayıf, ince',
    'LAL': 'dilsiz; lal',
    // 4 harf
    'KESK': 'yeşil',
    'ZÊR': 'altın; sarı',
    'SPÎ': 'beyaz',
    'GEWR': 'gri',
    'DENG': 'ses',
    'DEST': 'el',
    'GUND': 'köy',
    'HETA': 'kadar, -e dek',
    'SIBE': 'sabah; yarın',
    'GERM': 'sıcak',
    'SARD': 'soğuk',
    'XURT': 'güçlü',
    'NERM': 'yumuşak',
    'RAST': 'doğru; sağ',
    'BIRA': 'erkek kardeş',
    'XWEH': 'kız kardeş',
    'KANÎ': 'kaynak, pınar',
    'ÇIYA': 'dağ',
    'DEŞT': 'ova, düzlük',
    'KEÇA': 'kız (tamlama)',
    'TIRS': 'korku',
    'EVIN': 'sevgi, aşk',
    'DERD': 'dert, acı',
    'BEXT': 'şans, baht',
    'BERÎ': 'önce',
    'GIHA': 'ot, çimen',
    'EVÎN': 'sevgi, aşk',
    'GELO': 'acaba',
    'EGER': 'eğer',
    'NIHA': 'şimdi',
    'ŞERT': 'şart, koşul',
    'FIRR': 'uç (fiil)',
    'HOLE': 'avlu',
    'FIREH': 'geniş',
    'TOLA': 'intikam',
    // 5 harf
    'PAYÎZ': 'sonbahar',
    'KITÊB': 'kitap',
    'CARAN': 'zaman, kez',
    'XWEDÊ': 'Tanrı, Allah',
    'DILAN': 'kalpler; Dilan (isim)',
    'ŞEVÊN': 'geceler',
    'BERXW': 'kuzu',
    'ÇEMAN': 'çayırlar, otlaklar',
    'GOLÊN': 'göller',
    'GULAN': 'çiçekler; Mayıs ayı',
    'WÊRAN': 'harap, yıkık',
    'ÇÎYAN': 'dağlar',
    'DILOP': 'damla',
    'TIRÊJ': 'ışın, ışık demeti',
    'KULÎL': 'çiçek',
    'BARÎN': 'yağmak (yağmur/kar)',
    'BIYAN': 'yabancı',
    'HOZAN': 'şair, ozan',
    'REQAS': 'dansçı',
    'NIVÎS': 'yazı, metin',
    'KOVAR': 'dergi',
    'NEXŞE': 'harita; desen',
    'RÛPEL': 'sayfa',
    'QELEM': 'kalem',
    'MANGE': 'inek',
    'BERAN': 'koç (erkek koyun)',
    'NÊÇÎR': 'av, avcılık',
    'KERGE': 'tavuk',
    'GEWRE': 'büyük, geniş',
    'NEHÊN': 'gizli, sır',
    'KEDER': 'keder, üzüntü',
    'NAVÇE': 'bölge, ilçe',
    'SÎNOR': 'sınır',
    'AŞITÎ': 'barış',
    'ŞÎLAV': 'selam',
    'NÛJEN': 'modern, yeni',
    'MÎNAK': 'örnek',
    'BÎRAN': 'hatırlamak; kuyular',
    'KÊLEK': 'yan, taraf',
    'KELEK': 'sal (nehir taşıtı)',
    'WÊNEK': 'resim, fotoğraf',
    'TIRŞE': 'ekşi',
    'ÇEPIK': 'alkış; şaplak',
    'DESTE': 'demet; grup; sap',
    'ÇÎLEK': 'çilek',
    'KEZAL': 'ceylan',
    'NIŞAN': 'işaret, nişan',
    'XATIR': 'hatır, hatıra',
    'PIŞTÎ': 'sonra, arkasından',
    'HEBÛN': 'olmak, var olmak',
    'XWEZÎ': 'keşke',
    'SALAN': 'yıllar',
    'TATÎL': 'tatil',
    'SÊŞEM': 'Salı',
    'SALON': 'salon',
    'BERÎN': 'yaralamak; geçmek',
    'HELÎN': 'erimek; uçmak',
    'BAJAR': 'şehir',
    'WELAT': 'yurt, vatan',
    'MIROV': 'insan',
    'HEVAL': 'arkadaş',
    'BIHAR': 'ilkbahar',
    'HAVÎN': 'yaz',
    'DAYIK': 'anne',
    'ŞIVAN': 'çoban',
    'AZADÎ': 'özgürlük',
    'DIKAN': 'dükkân',
    'GIRAN': 'ağır; pahalı',
    'KESER': 'üzüntü',
    'RÛMET': 'onur, saygınlık',
    'ZEMÎN': 'zemin, yer',
    'KEVIR': 'taş',
    'BARAN': 'yağmur',
    'NEHIR': 'nehir',
    'ZANÎN': 'bilmek',
    'DAYÎK': 'anne',
    'BAJÊR': 'şehirde',
    'BAHOZ': 'fırtına',
    'MÊRIK': 'adam, erkek',
    'JINIK': 'kadın',
    'KEÇIK': 'genç kız',
    'JIYAN': 'hayat, yaşam',
    'GIYAN': 'ruh, nefes',
    'STÊRK': 'yıldız',
    'TOFAN': 'sel, tufan',
    'ZINAR': 'kayalık',
    'CIWAN': 'genç, güzel',
    'GUNDÎ': 'köylü',
    'MÊVAN': 'misafir',
    'SEROK': 'başkan',
    'MÎREK': 'bey, emir',
    'SIWAR': 'atlı, binici',
    'DELAL': 'sevgili, güzel',
    'HEKIM': 'doktor',
    'WEKÎL': 'vekil, avukat',
    'ZIMAN': 'dil (lisan)',
    'ÇÎROK': 'hikâye',
    'DÎROK': 'tarih',
    'KILAM': 'şarkı, türkü',
    'STRAN': 'şarkı',
    'BIZIN': 'keçi',
    'BERAZ': 'domuz',
    'KÛÇIK': 'köpek',
    'PISÎK': 'kedi',
    'HÊSAN': 'kolay',
    'MEZIN': 'büyük',
    'BIÇÛK': 'küçük',
    'SIVIK': 'hafif',
    'DIRÊJ': 'uzun',
    'BAKUR': 'kuzey',
    'BAŞÛR': 'güney',
    'ROJAV': 'batı',
    'ŞOREŞ': 'devrim',
    'MUZÎK': 'müzik',
    'PÎROZ': 'kutsal, mübarek',
    'XEBAT': 'çalışma, mücadele',
    'ŞIYAR': 'uyanık',
    'NÊZIK': 'yakın',
    'NÎVRO': 'öğle',
    'HELAL': 'helal',
    'RESIM': 'resim',
    'NEXWE': 'hasta',
    'DILŞA': 'mutlu, neşeli',
    'LAWIK': 'genç erkek',
    'ŞÎRÎN': 'tatlı',
    'XELAS': 'kurtarma; tamam',
    'ŞORBA': 'çorba',
    'XEBER': 'haber',
    'NARIN': 'ince, narin',
    'NÊZÎK': 'yakın',
    'GOTAR': 'konuşma, makale',
    'BEJNA': 'boy, endam',
    'KEÇEL': 'kel',
    'BIRÎN': 'yara; kesmek',
    'ŞEREF': 'şeref',
    'NAMÛS': 'namus',
    'HURMET': 'saygı, hürmet',
    'DILSOZ': 'sadık, vefalı',
    'DILPAK': 'temiz kalpli',
    'ABORÎ': 'ekonomik, mali',
    'DESTÊ': 'elin, elinden',
    'GIRTÎ': 'tutuklu, kapalı',
    'GOLEK': 'buzağı, dana',
    'HEFTÊ': 'hafta (tamlama)',
    'HEWŞE': 'avlu',
    'LEZAN': 'lezzet, tat',
    'NERÎN': 'bakmak, görmek',
    'NIRXE': 'değer, kıymet',
    'NISAN': 'Nisan (ay)',
    'NÊRÎN': 'erkek, eril',
    'PEMBE': 'pembe',
    'PÊDAN': 'vermek, sunmak',
    'QENÇÎ': 'iyilik, güzellik',
    'RONIN': 'oturmak, ikamet etmek',
    'SAATÊ': 'saatin, saate',
    'SERDE': 'dönem, çağ',
    'SERÊK': 'başlık, başlı',
    'SIBEH': 'sabah',
    'WELÊT': 'vatan, yurt',
    'ÇANDÎ': 'kültürel; ekilmiş',
    'ÇEMEK': 'dere, çay (küçük)',
    'ÇIQAS': 'ne kadar, kaç',
    'ÇÛBÛN': 'gitmek (geçmiş)',
    'ÊVARÊ': 'akşamleyin',
    'ŞAHID': 'tanık, şahit',
    'ŞEWAN': 'geceler',
    'ŞEWAT': 'yangın, ateş',
    // Yeni eklenenler
    'RÊBER': 'rehber, önder',
    'BAXÇE': 'bahçe',
    'ÇALAK': 'aktif, çalışkan',
    'DIWÊR': 'duvar',
    'WINDA': 'kaybolmuş, yitik',
    'BIHÊZ': 'güçlü, kuvvetli',
    'TENIK': 'ince, narin',
    'REWŞE': 'durum, hal',
    'FEQÎR': 'fakir, yoksul',
    'MÊRXE': 'kahraman, yiğit',
    'BERÊZ': 'saygın, şerefli',
    'QELEW': 'şişman, kalın',
    'ÇEPEL': 'kirli, pis',
    'EZMÛN': 'deneyim, sınav',
    'BÊDIL': 'üzgün, gönülsüz',
    'KELEM': 'lahana',
    'KELEJ': 'heyecanlı, aktif',
    'FIRÎN': 'uçmak',
    'ÇIMÊN': 'çayır, otlak',
    'NEXAŞ': 'usta, nakkaş',
    'RÛKAL': 'bol gömlek, cübbe',
    'HEVRA': 'birlikte, beraber',
    'ÇÎNAR': 'çınar ağacı',
    'GEWZE': 'ceviz',
    'JÊDER': 'kaynak, referans',
    'NIJAR': 'ince, zayıf',
    'ŞEMAL': 'kuzey rüzgarı',
    'BÊROJ': 'güneşsiz, şanssız',
    'ŞIKIR': 'şeker; teşekkür',
    'KELAM': 'söz, konuşma',
    'XWEŞÎ': 'sağlık, güzellik',
    'NÛBÛN': 'yenilenmek',
    'ÇÛYÎN': 'gitmek',
    'ÊVARE': 'akşam',
    'XEWNA': 'rüya (tamlama)',
    'ŞADÎN': 'neşeli; Şadîn (isim)',
    'NIŞTÎ': 'yerleşik, sakin',
    'KÊTOR': 'sepet',
    'DEWLE': 'kova, bakraç',
    'SERWA': 'hanım, prenses',
    // 6+ harf
    'WELÊTÎ': 'vatansever',
    'XWENDIN': 'okumak',
    'VEXWARIN': 'içmek',
    'RIZGARÎ': 'kurtuluş',
    'HEVKARÎ': 'işbirliği',
    'YEKÎTÎ': 'birlik',
    'SERKEFTÎ': 'başarılı',
    'ŞEREFDAR': 'şerefli',
    'NAVEND': 'merkez, orta',
  };

  static String? meaning(String word) => _meanings[word.toUpperCase()];
  static bool hasMeaning(String word) => _meanings.containsKey(word.toUpperCase());

  static List<({String word, String meaning})> get allEntries =>
      _meanings.entries.map((e) => (word: e.key, meaning: e.value)).toList();
}
